### ISSUE TITLE
Nothing happens when I target the crates.

### ISSUE THREAD

**Issue by IamCodyy** [Bunny5578/qb-crates#1]
If this is still being maintained, not sure but target doesn't work.

![image](https://github.com/Bunny5578/qb-crates/assets/6721888/201fd7c1-3823-4c3d-aef0-67f309851039)

**Comment by ivegotthis** [comment]
Hi, i don't own or work on this script but I thought I would just mention that there is no code in the script for 3rd eye, it's done via the radilmenu. You'll have to put the command in there.

**Comment by IamCodyy** [comment]
> Hi, i don't own or work on this script but I thought I would just mention that there is no code in the script for 3rd eye, it's done via the radilmenu. You'll have to put the command in there.

Thanks man!

**Comment by RobyB148** [comment]
what do i have to do to get the radial menu to work?
